### ISSUE TITLE
Crash in the learning engram when clicking around

### ISSUE THREAD

**Issue by ronickg** [BubbleTrouble14/ARKCraft#16]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 9/7/16 6:57 PM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 47
    at com.uberverse.arkcraft.common.engram.EngramManager.getEngram(EngramManager.java:181)
    at com.uberverse.arkcraft.common.container.player.ContainerEngram.setSelected(ContainerEngram.java:112)
    at com.uberverse.arkcraft.common.container.player.ContainerEngram$EngramSlot.func_82870_a(ContainerEngram.java:105)
    at com.uberverse.arkcraft.common.container.player.ContainerEngram.func_75144_a(ContainerEngram.java:54)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:492)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:390)
    at com.uberverse.arkcraft.client.gui.scrollable.GUIScrollable.func_73864_a(GUIScrollable.java:93)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
    at com.uberverse.arkcraft.client.gui.scrollable.GUIScrollable.func_146274_d(GUIScrollable.java:64)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1670)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.uberverse.arkcraft.common.engram.EngramManager.getEngram(EngramManager.java:181)
    at com.uberverse.arkcraft.common.container.player.ContainerEngram.setSelected(ContainerEngram.java:112)
    at com.uberverse.arkcraft.common.container.player.ContainerEngram$EngramSlot.func_82870_a(ContainerEngram.java:105)
    at com.uberverse.arkcraft.common.container.player.ContainerEngram.func_75144_a(ContainerEngram.java:54)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:492)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:390)
    at com.uberverse.arkcraft.client.gui.scrollable.GUIScrollable.func_73864_a(GUIScrollable.java:93)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
    at com.uberverse.arkcraft.client.gui.scrollable.GUIScrollable.func_146274_d(GUIScrollable.java:64)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
    Screen name: com.uberverse.arkcraft.client.gui.player.GUIEngram

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['BubbleTrouble14'/213, l='MpServer', x=217.46, y=79.00, z=57.51]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 220.00,64.00,256.00 - World: (220,64,256), Chunk: (at 12,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 6234653 game time, 1000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 112 total; [EntityPlayerSP['BubbleTrouble14'/213, l='MpServer', x=217.46, y=79.00, z=57.51], EntityItem['item.item.egg'/256, l='MpServer', x=257.34, y=80.00, z=20.75], EntityChicken['This is a "Dodo" , not a chick'/257, l='MpServer', x=254.69, y=80.00, z=21.50], EntityChicken['This is a "Dodo" , not a chick'/258, l='MpServer', x=257.50, y=80.00, z=24.28], EntitySkeleton['Skeleton'/259, l='MpServer', x=262.41, y=29.00, z=95.81], EntityZombie['Zombie'/260, l='MpServer', x=264.69, y=21.00, z=84.06], EntitySkeleton['Skeleton'/261, l='MpServer', x=265.00, y=20.00, z=71.16], EntityBat['Bat'/263, l='MpServer', x=244.25, y=46.38, z=95.91], EntitySkeleton['Skeleton'/519, l='MpServer', x=182.50, y=23.00, z=20.50], EntityCreeper['Creeper'/264, l='MpServer', x=265.50, y=40.00, z=93.50], EntitySkeleton['Skeleton'/265, l='MpServer', x=257.50, y=36.00, z=82.50], EntityBat['Bat'/266, l='MpServer', x=229.13, y=51.00, z=-0.50], EntitySkeleton['Skeleton'/269, l='MpServer', x=146.50, y=19.00, z=44.50], EntitySkeleton['Skeleton'/270, l='MpServer', x=145.50, y=19.00, z=45.50], EntityBat['Bat'/784, l='MpServer', x=225.69, y=50.00, z=-13.47], EntitySkeleton['Skeleton'/274, l='MpServer', x=277.81, y=30.00, z=69.75], EntitySpider['Spider'/275, l='MpServer', x=169.50, y=64.00, z=11.50], EntityWolf['A Big Wolf'/276, l='MpServer', x=254.72, y=80.00, z=7.41], EntityBat['Bat'/788, l='MpServer', x=206.13, y=38.44, z=51.72], EntityWolf['A Big Wolf'/277, l='MpServer', x=254.44, y=80.00, z=11.94], EntityBat['Bat'/789, l='MpServer', x=210.25, y=37.63, z=48.41], EntityWolf['A Big Wolf'/278, l='MpServer', x=255.81, y=80.00, z=10.84], EntityBat['Bat'/790, l='MpServer', x=202.72, y=40.03, z=53.72], EntityWolf['A Big Wolf'/279, l='MpServer', x=257.72, y=80.00, z=13.22], EntityBat['Bat'/791, l='MpServer', x=203.53, y=55.00, z=0.44], EntityCreeper['Creeper'/280, l='MpServer', x=256.50, y=29.00, z=110.50], EntityBat['Bat'/281, l='MpServer', x=264.59, y=17.10, z=107.13], EntityCreeper['Creeper'/282, l='MpServer', x=142.50, y=27.00, z=58.50], EntityCreeper['Creeper'/283, l='MpServer', x=264.50, y=42.00, z=-14.50], EntityCreeper['Creeper'/285, l='MpServer', x=261.50, y=41.00, z=-13.50], EntityZombie['Zombie'/297, l='MpServer', x=274.34, y=20.00, z=125.06], EntitySkeleton['Skeleton'/310, l='MpServer', x=153.50, y=21.00, z=-16.94], EntityCreeper['Creeper'/825, l='MpServer', x=178.47, y=64.00, z=19.03], EntityPainting['Painting'/66, l='MpServer', x=205.97, y=73.50, z=190.00], EntityPainting['Painting'/67, l='MpServer', x=196.00, y=74.00, z=185.97], EntityPainting['Painting'/68, l='MpServer', x=202.03, y=73.50, z=190.00], EntityArmorStand['Armor Stand'/69, l='MpServer', x=192.50, y=67.00, z=187.50], EntityPainting['Painting'/70, l='MpServer', x=203.03, y=73.50, z=194.50], EntityPainting['Painting'/71, l='MpServer', x=204.50, y=73.50, z=195.97], EntitySkeleton['Skeleton'/583, l='MpServer', x=259.72, y=14.00, z=105.25], EntitySpider['Spider'/593, l='MpServer', x=274.28, y=25.09, z=48.06], EntityPainting['Painting'/121, l='MpServer', x=259.00, y=75.50, z=135.03], EntityPainting['Painting'/123, l='MpServer', x=259.00, y=75.50, z=139.97], EntityPainting['Painting'/124, l='MpServer', x=261.03, y=75.50, z=133.50], EntityPainting['Painting'/129, l='MpServer', x=263.97, y=80.50, z=144.50], EntityPainting['Painting'/66, l='MpServer', x=205.97, y=73.50, z=190.00], EntityPainting['Painting'/67, l='MpServer', x=196.00, y=74.00, z=185.97], EntityPainting['Painting'/68, l='MpServer', x=202.03, y=73.50, z=190.00], EntityCreeper['Creeper'/627, l='MpServer', x=276.50, y=25.00, z=121.50], EntityZombie['Zombie'/884, l='MpServer', x=161.50, y=24.02, z=81.50], EntityPainting['Painting'/70, l='MpServer', x=203.03, y=73.50, z=194.50], EntityPainting['Painting'/71, l='MpServer', x=204.50, y=73.50, z=195.97], EntityPainting['Painting'/121, l='MpServer', x=259.00, y=75.50, z=135.03], EntityItemFrame['entity.ItemFrame.name'/122, l='MpServer', x=262.97, y=76.50, z=138.50], EntityPainting['Painting'/123, l='MpServer', x=259.00, y=75.50, z=139.97], EntityPainting['Painting'/124, l='MpServer', x=261.03, y=75.50, z=133.50], EntityItemFrame['entity.ItemFrame.name'/125, l='MpServer', x=262.97, y=76.50, z=136.50], EntityItemFrame['entity.ItemFrame.name'/126, l='MpServer', x=262.97, y=76.50, z=137.50], EntityItemFrame['entity.ItemFrame.name'/127, l='MpServer', x=262.97, y=75.50, z=138.50], EntityArmorStand['Armor Stand'/128, l='MpServer', x=263.50, y=79.00, z=147.50], EntityPainting['Painting'/129, l='MpServer', x=263.97, y=80.50, z=144.50], EntitySkeleton['Skeleton'/897, l='MpServer', x=275.50, y=45.02, z=-20.50], EntityCreeper['Creeper'/902, l='MpServer', x=205.50, y=51.02, z=-5.50], EntityCreeper['Creeper'/903, l='MpServer', x=206.50, y=51.02, z=-5.50], EntitySheep['Sheep'/146, l='MpServer', x=296.13, y=80.00, z=129.22], EntityZombie['Zombie'/659, l='MpServer', x=175.53, y=55.00, z=-22.06], EntitySpider['Spider'/408, l='MpServer', x=197.50, y=57.00, z=12.50], EntityCreeper['Creeper'/427, l='MpServer', x=256.50, y=41.00, z=125.50], EntitySkeleton['Skeleton'/428, l='MpServer', x=255.50, y=41.00, z=124.50], EntitySkeleton['Skeleton'/456, l='MpServer', x=259.50, y=22.00, z=68.50], EntityItem['item.item.dyePowder.black'/214, l='MpServer', x=208.16, y=25.00, z=56.19], EntityBat['Bat'/215, l='MpServer', x=205.34, y=38.69, z=51.53], EntityCreeper['Creeper'/727, l='MpServer', x=264.50, y=46.00, z=118.50], EntitySkeleton['Skeleton'/216, l='MpServer', x=206.94, y=64.00, z=59.47], EntityCreeper['Creeper'/728, l='MpServer', x=259.63, y=46.00, z=114.94], EntityArmorStand['Armor Stand'/217, l='MpServer', x=213.50, y=80.00, z=51.50], EntityItemFrame['entity.ItemFrame.name'/218, l='MpServer', x=214.03, y=80.50, z=63.50], EntityArmorStand['Armor Stand'/219, l='MpServer', x=213.50, y=80.00, z=55.50], EntitySpider['Spider'/475, l='MpServer', x=185.50, y=13.00, z=111.50], EntityEnderman['Enderman'/731, l='MpServer', x=204.50, y=50.00, z=139.13], EntityItemFrame['entity.ItemFrame.name'/220, l='MpServer', x=214.03, y=80.50, z=62.50], EntityEnderman['Enderman'/732, l='MpServer', x=203.50, y=50.00, z=129.50], EntityArmorStand['Armor Stand'/221, l='MpServer', x=213.50, y=80.00, z=57.50], EntityEnderman['Enderman'/733, l='MpServer', x=205.38, y=50.00, z=134.75], EntityItemFrame['entity.ItemFrame.name'/222, l='MpServer', x=214.03, y=80.50, z=60.50], EntityZombie['Zombie'/734, l='MpServer', x=203.50, y=50.00, z=130.50], EntityItemFrame['entity.ItemFrame.name'/223, l='MpServer', x=214.03, y=80.50, z=61.50], EntityItemFrame['entity.ItemFrame.name'/224, l='MpServer', x=214.03, y=82.50, z=63.50], EntityItemFrame['entity.ItemFrame.name'/225, l='MpServer', x=214.03, y=80.50, z=59.50], EntityArmorStand['Armor Stand'/226, l='MpServer', x=213.50, y=80.00, z=53.50], EntityItemFrame['entity.ItemFrame.name'/227, l='MpServer', x=214.03, y=82.50, z=62.50], EntityCreeper['Creeper'/228, l='MpServer', x=206.50, y=29.00, z=57.50], EntityEnderman['Enderman'/229, l='MpServer', x=205.47, y=59.00, z=54.84], EntitySkeleton['Skeleton'/231, l='MpServer', x=203.91, y=66.00, z=23.56], EntityZombie['Zombie'/487, l='MpServer', x=218.50, y=28.00, z=36.50], EntityBat['Bat'/232, l='MpServer', x=220.84, y=30.28, z=37.66], EntityZombie['Zombie'/488, l='MpServer', x=221.50, y=28.00, z=39.50], EntityItem['item.item.rottenFlesh'/233, l='MpServer', x=236.22, y=83.00, z=44.41], EntityZombie['Zombie'/235, l='MpServer', x=193.94, y=17.00, z=8.53], EntityBat['Bat'/236, l='MpServer', x=210.47, y=47.00, z=25.53], EntitySkeleton['Skeleton'/492, l='MpServer', x=273.69, y=17.32, z=136.00], EntityCreeper['Creeper'/237, l='MpServer', x=236.50, y=23.00, z=92.50], EntitySkeleton['Skeleton'/238, l='MpServer', x=226.50, y=77.00, z=76.88], EntityItem['item.item.egg'/241, l='MpServer', x=255.19, y=80.00, z=23.19], EntityBat['Bat'/242, l='MpServer', x=264.25, y=46.06, z=108.22], EntityBat['Bat'/249, l='MpServer', x=262.47, y=21.44, z=92.47], EntityBat['Bat'/250, l='MpServer', x=259.03, y=22.75, z=81.84], EntitySkeleton['Skeleton'/251, l='MpServer', x=257.88, y=22.00, z=76.47], EntityBat['Bat'/252, l='MpServer', x=267.56, y=20.70, z=63.88], EntityZombie['Zombie'/509, l='MpServer', x=265.50, y=29.00, z=77.50], EntityZombie['Zombie'/254, l='MpServer', x=170.50, y=23.00, z=24.50], EntityZombie['Zombie'/255, l='MpServer', x=179.03, y=62.00, z=6.31]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 226018232 bytes (215 MB) / 523501568 bytes (499 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.4.1563.jar) 
    UCHIJA  Forge{11.14.4.1563} [Minecraft Forge](forge-1.8-11.14.4.1563.jar) 
    UCHIJA  arkcraft{alpha-1.000-preview-5} [ARKCraft](arkcraft-alpha-1.000-preview-5.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    Launched Version: 1.8-forge1.8-11.14.4.1563
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by ronickg** [comment]
Wait, it happens when u click on a empty Engram Slot.
